name: "Textile Bucket - Deploy"
on:
  push:
    branches:
      - master
jobs:
  deploy: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: |
          npm run install
          npm run build
      - name: push # push to a known bucket
        id: bucket
        uses: textileio/github-action-buckets@master
        with:
          key: ${{ secrets.TEXTILE_ACCOUNT_KEY }}
          secret: ${{ secrets.TEXTILE_ACCOUNT_SECRET }}
          bucket: "public"
          thread: ${{ secrets.TEXTILE_ORG_BUCKET_THREAD }}
          path: "/dist"
          pattern: "**/*"
      - run: echo "bucket - ${{ steps.bucket.outputs.key }}"
      - run: echo "ipfs - ${{ steps.bucket.outputs.ipfs }}"
      - run: echo "ipfs link - ${{ steps.bucket.outputs.ipfsUrl }}"
      - run: echo "ipns - ${{ steps.bucket.outputs.ipns }}"
      - run: echo "ipns link - ${{ steps.bucket.outputs.ipnsUrl }}"
      - run: echo "hub - ${{ steps.bucket.outputs.hub }}"
      - run: echo "www - ${{ steps.bucket.outputs.www }}"